#!/usr/bin/env node
// ─────────────────────────────────────────────
//  MeowNet Idle Engine — Fork CLI
//  Run: node scripts/create-fork.js
// ─────────────────────────────────────────────

const readline = require('readline');
const fs = require('fs');
const path = require('path');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const q = (prompt) => new Promise(resolve => rl.question(prompt, resolve));

async function main() {
  console.log('\n🐾 MeowNet Idle Engine — Fork Generator\n');

  const gameName     = await q('Game name (e.g. "Space Miners"): ');
  const gameId       = await q('Game ID, no spaces (e.g. "space-miners"): ');
  const gameSlug     = gameId.toLowerCase().replace(/\s+/g, '-');
  const primaryName  = await q('Primary resource name (e.g. "Ore"): ');
  const primaryIcon  = await q('Primary resource emoji (e.g. "⛏"): ');
  const buildingName = await q('First building name (e.g. "Miner"): ');
  const buildingIcon = await q('First building emoji (e.g. "👷"): ');
  const buildingDesc = await q('First building description: ');
  const primaryColor = await q('Primary color hex (e.g. "#4A90E2"): ');
  const accentColor  = await q('Accent color hex (e.g. "#FFD166"): ');
  const bgColor      = await q('Background color hex (e.g. "#0A0E1A"): ');
  const prestigeName = await q('Prestige currency name (e.g. "Stars"): ');
  const prestigeIcon = await q('Prestige currency emoji (e.g. "⭐"): ');
  const locale       = await q('Default locale (en/es/fr/ja) [en]: ') || 'en';

  const resourceId  = primaryName.toLowerCase().replace(/\s+/g, '_');
  const buildingId  = buildingName.toLowerCase().replace(/\s+/g, '_');

  const config = `// ${gameName} — Game Config (generated by MeowNet Fork CLI)
import { GameConfig, AchievementDef, PrestigeUpgradeDef, ChallengeDef } from '../types/engine';

export const gameConfig: GameConfig = {
  gameId: '${gameId}',
  gameName: '${gameName}',
  version: '1.0.0',
  locale: '${locale}',
  resources: [{
    id: '${resourceId}', name: '${primaryName}', icon: '${primaryIcon}',
    startingValue: 0, cap: 'infinite', displayPrecision: 1,
  }],
  buildings: [{
    id: '${buildingId}', name: '${buildingName}', icon: '${buildingIcon}',
    description: '${buildingDesc}',
    baseCost: { ${resourceId}: 10 }, costScaling: 1.15,
    baseProduction: { ${resourceId}: 0.1 },
  }],
  upgrades: [{
    id: '${buildingId}_boost', name: '${buildingName} Boost',
    description: 'Double ${buildingName} production.', icon: '⚡',
    cost: { ${resourceId}: 100 },
    effect: { type: 'building_multiplier', targetId: '${buildingId}', multiplier: 2 },
    unlockCondition: { buildingId: '${buildingId}', buildingCount: 5 },
  }],
  prestige: {
    enabled: true, requiredResource: '${resourceId}', requiredAmount: 1_000_000,
    currencyName: '${prestigeName}', currencyIcon: '${prestigeIcon}',
    formulaExponent: 0.5, persistedUpgrades: [],
  },
  achievements: [], prestigeShop: [], dailyChallenges: [],
  theme: {
    primaryColor: '${primaryColor}', accentColor: '${accentColor}',
    backgroundColor: '${bgColor}', surfaceColor: '#1A1025', textColor: '#F5EFE6',
  },
  balance: { tickRateMs: 100, offlineEarningsRate: 0.5, maxOfflineHours: 8, tapProductionMultiplier: 1 },
  notifications: {
    enabled: true, reEngagementHours: 4, prestigeReadyAlert: true, dailyChallengeAlert: true,
    messages: {
      reEngagement: ['Your ${buildingName}s are waiting! Come back!'],
      prestigeReady: '${prestigeIcon} Ready to Prestige!',
      dailyReset: 'New daily challenges available!',
    },
  },
  sound: {
    enabled: true, volume: 0.6,
    sounds: { tap: 'builtin:tap', purchase: 'builtin:purchase', upgrade: 'builtin:upgrade',
      achievement: 'builtin:achievement', prestige: 'builtin:prestige', milestone: 'builtin:milestone' },
  },
  remote: {
    supabaseUrl: process.env.EXPO_PUBLIC_SUPABASE_URL!,
    supabaseAnonKey: process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY!,
    gameSlug: '${gameSlug}',
  },
};

export const achievements: AchievementDef[] = [
  { id: 'first_resource', name: 'First ${primaryName}', description: 'Collect your first ${primaryName}.', icon: '${primaryIcon}', trigger: { type: 'resource_total', resourceId: '${resourceId}', amount: 1 } },
  { id: 'first_building', name: 'First ${buildingName}', description: 'Hire your first ${buildingName}.', icon: '${buildingIcon}', trigger: { type: 'building_count', buildingId: '${buildingId}', count: 1 } },
];
export const prestigeShopItems: PrestigeUpgradeDef[] = [
  { id: 'prestige_global', name: 'Power Surge', description: 'All production x2.', icon: '⚡', cost: 5, maxLevel: 5, effect: { type: 'global_multiplier', value: 2 } },
];
export const dailyChallenges: ChallengeDef[] = [
  { id: 'daily_tap', title: 'Tap Attack', description: 'Tap 200 times.', icon: '👆', goalType: 'tap_count', goalAmount: 200, reward: { type: 'resource', resourceId: '${resourceId}', amount: 500 } },
];
`;

  const outPath = path.join(process.cwd(), 'src', 'config', 'gameConfig.' + gameId + '.ts');
  fs.writeFileSync(outPath, config);
  console.log('\n✅ Generated: ' + outPath);
  console.log('\nNext steps:');
  console.log('  1. Rename to gameConfig.ts (backup current first)');
  console.log('  2. Customize buildings, upgrades, achievements');
  console.log('  3. Set .env Supabase keys');
  console.log('  4. npx expo run:ios\n');
  rl.close();
}

main().catch(err => { console.error(err); process.exit(1); });
